[agent]
LIVEKIT_URL = "wss://glosos-uti53aki.livekit.cloud"
GOOGLE_CREDENTIALS_FILE = "google-service-account.json"
STT_MODEL = "latest_long"
LLM_MODEL = "gemini-3-flash"
TTS_MODEL = "chirp_3"
TTS_VOICE_NAME = "en-US-Chirp3-HD-Charon"
GOOGLE_STT_LOCATION = "eu"
GOOGLE_LLM_LOCATION = "global"
STT_LANGUAGE = "en-US"
STT_USE_STREAMING = true
MIN_ENDPOINTING_DELAY = 0.1
MAX_ENDPOINTING_DELAY = 0.6
